export const USER_PROFILE_CONSTANTS = {
    VALIDATION: {
        MAX_FIRST_NAME_LENGTH: 100,
        MAX_LAST_NAME_LENGTH: 100,
        MAX_BIO_LENGTH: 1000,
        MAX_IMAGE_LENGTH: 255,
        MAX_LOCATION_LENGTH: 255,
        MAX_WEBSITE_LENGTH: 255,
    },
};